version: '3.8'

services:
  frontend:
    build:
      context: ./time-manager-frontend
      dockerfile: Dockerfile
    container_name: time-manager-frontend
    ports:
      - "8080:80"
    networks:
      - app_net

  api:
    build:
      context: ./time-manager-backend
      dockerfile: Dockerfile
    container_name: time-manager-backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "ecto://postgres:postgres@db/time_manager_db"
      SECRET_KEY_BASE: "cGFMwXKImwcdyDGCZhsZPprFxBb37FbQqRoUa+plpZtmGX3bm8+HvwDiivYojwLT"
      PORT: 4000
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:14
    container_name: time-manager-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: time_manager_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

networks:
  app_net:

volumes:
  db_data:
